[package]
edition = "2018"
authors = [
    "Arko <arko2600@gmail.com>",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
description = "Peripheral access API for STM32L0 series microcontrollers"
documentation = "https://docs.rs/crate/stm32l0xx-hal"

keywords = [
    "arm",
    "cortex-m",
    "stm32l0xx",
    "hal",
]
license = "0BSD"
name = "stm32l0xx-hal"
readme = "README.md"
repository = "https://github.com/stm32-rs/stm32l0xx-hal"
version = "0.1.6"

[package.metadata.docs.rs]
features = ["stm32l0x1", "stm32l0x2", "rt"]

[dependencies]
embedded-hal = { version = "0.2.3", features = ["unproven"] }
cortex-m = {version = "0.5.8", features = ["const-fn"] }
cortex-m-rt = "0.6.8"
cortex-m-semihosting = "0.3.2"
cortex-m-rtfm = "0.4.3"
void = { version = "1.0.2", default-features = false }
cast = { version = "0.2.2", default-features = false }
nb = "0.1.2"

[dependencies.stm32l0]
version = "0.7.0"

[dev-dependencies]
panic-halt = "0.2.0"
panic-semihosting = "0.5.1"

[features]
rt = ["stm32l0/rt"]
stm32l0x1 = ["stm32l0/stm32l0x1"]
stm32l0x2 = ["stm32l0/stm32l0x2"]

[profile.dev]
codegen-units = 1
incremental = false
debug = true
opt-level = "s"

[profile.release]
codegen-units = 1
lto = true
debug = true
opt-level = "s"


[[example]]
name = "button_irq"
required-features = ["rt"]

[[example]]
name = "button_irq_rtfm"
required-features = ["rt"]

[[example]]
name = "timer"
required-features = ["rt"]

[[example]]
name = "timer_interrupt_rtfm"
required-features = ["rt"]

[[example]]
name = "adc_pwm"
required-features = ["stm32l0x1"]

[[example]]
name = "pwm"
required-features = ["stm32l0x1"]
